### ISSUE TITLE
real fields are treated as integers

### ISSUE THREAD

**Issue by tombriggsallego** [firebend/pipelinewise-tap-mssql#19]
This tap considers a field of type 'real' to be an integer and reports it in schema messages as such. That can cause problems when the target tries to load the data; loading into Postgres fails, for example, because the field will be created as an int, and inserting decimal values into it fails.

The fix is as simple as moving the real type from the BYTES_FOR_INTEGER_TYPE dict to the BYTES_FOR_INTEGER_TYPE set. I've tested that locally, and more importantly, this has already been fixed [upstream](https://github.com/wintersrd/pipelinewise-tap-mssql/commit/06646cf5d889bfe3d5586e9086e23e076811f1ab).

**Comment by zyzil** [comment]
Thanks @tombriggsallego for the heads up and sorry for the delay, I'm working on getting this merged in.

**Comment by tombriggsallego** [comment]
Awesome, thanks @zyzil !
